ASP.Net/ViewBagTest/ViewBagTest/Models/ErrorViewModel.cs
namespace ViewBagTest.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP.Net/ViewBagTest/ViewBagTest/Models/Student.cs
using System.ComponentModel;

namespace ViewBagTest.Models
{
    public class Student
    {
        public int StudentId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string EnrollmentNo { get; set; }

    }



}

ASP.Net/ViewBagTest/ViewBagTest/Models/Teacher.cs
namespace ViewBagTest.Models
{
    public class Teacher
    {
        public int TeacherId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        
    }
}

ASP.Net/ViewBagTest/ViewBagTest/Models/ViewModel.cs
namespace ViewBagTest.Models
{
    public class ViewModel
    {
        public IEnumerable<Teacher> Teachers { get; set; }
        public IEnumerable<Student> Students { get; set; }
    }
}

ASP.Net/ViewBagTest/ViewBagTest/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ViewBagTest.Models;

namespace ViewBagTest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP.Net/ViewBagTest/ViewBagTest/Controllers/MultipleModelInOneViewController.cs
using Microsoft.AspNetCore.Mvc;
using System.Dynamic;
using ViewBagTest.Models;

namespace ViewBagTest.Controllers
{
    public class MultipleModelInOneViewController : Controller
    {
        public List<Teacher> GetTeachers()
        {
            List<Teacher> teachers = new List<Teacher>();
            teachers.Add(new Teacher { TeacherId = 1, Code = "TT", Name = "Tejas Trivedi" });
            teachers.Add(new Teacher { TeacherId = 2, Code = "JT", Name = "Jignesh Trivedi" });
            teachers.Add(new Teacher { TeacherId = 3, Code = "RT", Name = "Rakesh Trivedi" });
            return teachers;
        }
        public List<Student> GetStudents()
        {
            List<Student> students = new List<Student>();
            students.Add(new Student { StudentId = 1, Code = "L0001", Name = "Amit Gupta", EnrollmentNo = "201404150001" });
            students.Add(new Student { StudentId = 2, Code = "L0002", Name = "Chetan Gujjar", EnrollmentNo = "201404150002" });
            students.Add(new Student { StudentId = 3, Code = "L0003", Name = "Bhavin Patel", EnrollmentNo = "201404150003" });
            return students;
        }
        public IActionResult Index()
        {
            ViewBag.Message = "Using Dynamic Model";
            dynamic mymodel = new ExpandoObject();
            mymodel.Teachers = GetTeachers();
            mymodel.Students = GetStudents();
            return View(mymodel);
        }

        public ActionResult IndexViewModel()
        {
            ViewBag.Message = "Using View Model!";
            ViewModel mymodel = new ViewModel();
            mymodel.Teachers = GetTeachers();
            mymodel.Students = GetStudents();
            return View(mymodel);
        }
        public ActionResult IndexViewData()
        {
            ViewBag.Message = "Index View Data!";
            ViewData["Teachers"] = GetTeachers();
            ViewData["Students"] = GetStudents();
            return View();
        }

        public ActionResult IndexViewBag()
        {
            ViewBag.Message = "Index View Bag!";
            ViewBag.Teachers = GetTeachers();
            ViewBag.Students = GetStudents();
            return View();
        }

        public ActionResult IndexTuple()
        {
            ViewBag.Message = "Index Tuple!";
            var tupleModel = new Tuple<List<Teacher>, List<Student>>(GetTeachers(), GetStudents());
            return View(tupleModel);
        }
        public ActionResult PartialView()
        {
            ViewBag.Message = "Welcome to my demo!";
            return View();
        }

        /// <summary>
        /// Render Teacher List
        /// </summary>
        /// <returns></returns>
        public PartialViewResult RenderTeacher()
        {
            return PartialView(GetTeachers());
        }

        /// <summary>
        /// Render Student List
        /// </summary>
        /// <returns></returns>
        public PartialViewResult RenderStudent()
        {
            return PartialView(GetStudents());
        }

    }

}

ASP.Net/ViewBagTest/ViewBagTest/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using ViewBagTest.Models;

namespace ViewBagTest.Controllers
{
    public class StudentController : Controller
    {
        /*IList<Student> studentList = new List<Student>() {
                    new Student(){ StudentID=1, StudentName="Steve", Age = 21 },
                    new Student(){ StudentID=2, StudentName="Bill", Age = 25 },
                    new Student(){ StudentID=3, StudentName="Ram", Age = 20 },
                    new Student(){ StudentID=4, StudentName="Ron", Age = 31 },
                    new Student(){ StudentID=5, StudentName="Rob", Age = 19 }
                };
        public IActionResult Index()
        {
            ViewBag.TotalStudents = studentList.Count();
            ViewBag.Student = studentList[1];

            ViewBag.Developer = "Zachary";

            return View();
        }
        public IActionResult Details()
        {
            ViewBag.Students = studentList[1];
            ViewBag.Developer = "Zachary";

            return View();
        }*/

    }
}

ASP.Net/ViewBagTest/ViewBagTest/Views/MultipleModelInOneView/Index.cshtml
@using ViewBagTest;
@model dynamic
@{
    ViewBag.Title = "Home Page";
}
<h2>@ViewBag.Message</h2>

<p><b>Teacher List</b></p>

<table>
    <tr>
        <th>Id</th>
        <th>Code</th>
        <th>Name</th>
    </tr>
    @foreach (Teacher teacher in Model.Teachers)
    {
        <tr>
            <td>@teacher.TeacherId</td>
            <td>@teacher.Code</td>
            <td>@teacher.Name</td>
        </tr>
    }
</table>

<p><b>Student List</b></p>

<table>
    <tr>
        <th>Id</th>
        <th>Code</th>
        <th>Name</th>
        <th>Enrollment No</th>
    </tr>
    @foreach (Student student in Model.Students)
    {
        <tr>
            <td>@student.StudentId</td>
            <td>@student.Code</td>
            <td>@student.Name</td>
            <td>@student.EnrollmentNo</td>
        </tr>
    }
</table>

ASP.Net/ViewBagTest/ViewBagTest/Views/MultipleModelInOneView/IndexTuple.cshtml
@using ViewBagTest;
@*@model Tuple <List<Teacher>, List <Student>>*@
@{
    ViewBag.Title = "Home Page";
}
<h2>@ViewBag.Message</h2>
<p><b>Teacher List</b></p>
<table>
    <tr>
        <th>Id</th>
        <th>Code</th>
        <th>Name</th>
    </tr>
    @foreach (Teacher teacher in Model.Item1)
    {
        <tr>
            <td>@teacher.TeacherId</td>
            <td>@teacher.Code</td>
            <td>@teacher.Name</td>
        </tr>
    }
</table>
<p><b>Student List</b></p>
<table>
    <tr>
        <th>Id</th>
        <th>Code</th>
        <th>Name</th>
        <th>Enrollment No</th>
    </tr>
    @foreach (Student student in Model.Item2)
    {
        <tr>
            <td>@student.StudentId</td>
            <td>@student.Code</td>
            <td>@student.Name</td>
            <td>@student.EnrollmentNo</td>
        </tr>
    }
</table>

ASP.Net/ViewBagTest/ViewBagTest/Views/MultipleModelInOneView/IndexViewBag.cshtml
@using ViewBagTest;
@{
    ViewBag.Title = "Home Page";
}
<h2>@ViewBag.Message</h2>

<p><b>Teacher List</b></p>

<table>
    <tr>
        <th>Id</th>
        <th>Code</th>
        <th>Name</th>
    </tr>
    @foreach (Teacher teacher in ViewBag.Teachers)
    {
            <tr>
                <td>@teacher.TeacherId</td>
                <td>@teacher.Code</td>
                <td>@teacher.Name</td>
            </tr>
    }
</table>

<p><b>Student List</b></p>

<table>
    <tr>
        <th>Id</th>
        <th>Code</th>
        <th>Name</th>
        <th>Enrollment No</th>
    </tr>
    @foreach (Student student in ViewBag.Students)
    {
            <tr>
                <td>@student.StudentId</td>
                <td>@student.Code</td>
                <td>@student.Name</td>
                <td>@student.EnrollmentNo</td>
            </tr>
    }
</table>

ASP.Net/ViewBagTest/ViewBagTest/Views/MultipleModelInOneView/IndexViewData.cshtml
@using ViewBagTest;
@{
    ViewBag.Title = "Home Page";
}
<h2>@ViewBag.Message</h2>
 <p><b>Teacher List</b></p>
@{

    IEnumerable<Teacher> teachers = ViewData["Teachers"] as IEnumerable<Teacher>;
    IEnumerable<Student> students = ViewData["Students"] as IEnumerable<Student>;
}
<table>
    <tr>
        <th>Id</th>
        <th>Code</th>
        <th>Name</th>
    </tr>
    @foreach (Teacher teacher in teachers)
    {
            <tr>
                <td>@teacher.TeacherId</td>
                <td>@teacher.Code</td>
                <td>@teacher.Name</td>
            </tr>
    }
</table>
 <p><b>Student List</b></p>
<table>
    <tr>
        <th>Id</th>
        <th>Code</th>
        <th>Name</th>
        <th>Enrollment No</th>
    </tr>
    @foreach (Student student in students)
    {
            <tr>
                <td>@student.StudentId</td>
                <td>@student.Code</td>
                <td>@student.Name</td>
                <td>@student.EnrollmentNo</td>
            </tr>
    }
</table>

ASP.Net/ViewBagTest/ViewBagTest/Views/MultipleModelInOneView/IndexViewModel.cshtml
@using ViewBagTest;
@model ViewModel
@{
    ViewBag.Title = "Home Page";
}
<h2>@ViewBag.Message</h2>

<p><b>Teacher List</b></p>

<table>
    <tr>
        <th>Id</th>
        <th>Code</th>
        <th>Name</th>
    </tr>
    @foreach (Teacher teacher in Model.Teachers)
    {
        <tr>
            <td>@teacher.TeacherId</td>
            <td>@teacher.Code</td>
            <td>@teacher.Name</td>
        </tr>
    }
</table>

<p><b>Student List</b></p>

<table>
    <tr>
        <th>Id</th>
        <th>Code</th>
        <th>Name</th>
        <th>Enrollment No</th>
    </tr>
    @foreach (Student student in Model.Students)
    {
        <tr>
            <td>@student.StudentId</td>
            <td>@student.Code</td>
            <td>@student.Name</td>
            <td>@student.EnrollmentNo</td>
        </tr>
    }
</table>

ASP.Net/ViewBagTest/ViewBagTest/Views/MultipleModelInOneView/PartialView.cshtml
@{
   ViewBag.Title = "Partial View";
}
<h2>@ViewBag.Message</h2>
<div>
    @{
        //Html.RenderAction("RenderTeacher");
        //Html.RenderAction("RenderStudent");
        
    }
</div>

ASP.Net/ViewBagTest/ViewBagTest/Views/MultipleModelInOneView/RenderStudent.cshtml
@using ViewBagTest;
@model IEnumerable<ViewBagTest.Models.Student>

<p><b>Student List</b></p>
<table>
    <tr>
        <th>Id</th>
        <th>Code</th>
        <th>Name</th>
        <th>Enrollment No</th>
    </tr>
    @foreach (Student student in Model)
    {
            <tr>
                <td>@student.StudentId</td>
                <td>@student.Code</td>
                <td>@student.Name</td>
                <td>@student.EnrollmentNo</td>
            </tr>
    }
</table>

ASP.Net/ViewBagTest/ViewBagTest/Views/MultipleModelInOneView/RenderTeacher.cshtml
@using ViewBagTest;
@model IEnumerable<ViewBagTest.Models.Teacher>
 <p><b>Teacher List</b></p>
<table>
    <tr>
        <th>Id</th>
        <th>Code</th>
        <th>Name</th>
    </tr>
    @foreach (Teacher teacher in Model)
    {
            <tr>
                <td>@teacher.TeacherId</td>
                <td>@teacher.Code</td>
                <td>@teacher.Name</td>
            </tr>
    }
</table>

ASP.Net/ViewBagTest/ViewBagTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ViewBagTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ViewBagTest.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ViewBagTest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MultipleModelInOneView" asp-action="Index">Dynamic Model</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MultipleModelInOneView" asp-action="IndexViewModel">Index View Model</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MultipleModelInOneView" asp-action="IndexViewData">Index View Data</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MultipleModelInOneView" asp-action="IndexViewBag">Index View Bag</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MultipleModelInOneView" asp-action="IndexTuple">Index Tuple</a>
                        </li>
                                                <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MultipleModelInOneView" asp-action="PartialView">Partial View</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MultipleModelInOneView" asp-action="RenderTeacher">Render Teacher</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MultipleModelInOneView" asp-action="RenderStudent">Render Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ViewBagTest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ASP.Net/ViewBagTest/ViewBagTest/Views/Student/Details.cshtml
@model ViewBagTest.Models.Student

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index2</title>
</head>
<body>

@*<div>
    <h4>Student</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StudentID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StudentID) 
            ID
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StudentName) "Name"
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StudentName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StudentEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StudentEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
    </dl>
</div>*@
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>
</body>
</html>

ASP.Net/ViewBagTest/ViewBagTest/Views/Student/Index.cshtml
@model ViewBagTest.Models.Student

<label>Total Students:</label>  @ViewBag.TotalStudents
<label>Developer:</label>  @ViewBag.Developer

<@*div>
    <h4>Student</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StudentID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StudentID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StudentName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StudentName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StudentEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StudentEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
    </dl>
</div>*@